name: CI Pipeline

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Train the model
        run: |
          python src/train.py

      - name: Build Docker image
        run: |
          docker build -t mlops-model .

      - name: Run Docker container
        run: |
          docker run --rm mlops-model

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag mlops-model ${{ secrets.DOCKER_USERNAME }}/mlops-model
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-model
