name: Prediction Model

on:
  push:
    branches:
      - docker_ci 

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Train the model
        run: |
          python src/train.py

      - name: Build Docker image
        run: |
          docker build -t mlops-model

      - name: Run Docker container
        run: |
          docker run --rm mlops-model
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
         docker tag mlops-pipeline ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest
